language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
 - xvfb

script: 
  - ./download_other_githubs
  # Console
  - qmake -qt=qt5 ToolMazeCreatorConsole.pro
  - make debug --silent
  - ./ToolMazeCreatorConsole
  # Desktop
  - qmake -qt=qt5 ToolMazeCreatorDesktop.pro
  - make debug --silent
  - ./ToolMazeCreatorDesktop &
  - sudo killall ToolMazeCreatorDesktop
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)